#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

paraFoam -builtin -touch

# runApplication setFields 

## Parallel
runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

# postProcess -func sampleAlongLine -latestTime

#------------------------------------------------------------------------------
